language: php
dist: precise
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
install:
  - composer install
script:
  - phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry vendor/bin/coveralls -v
